namespace Inferno
{
    public enum MahAppsAccent : byte
    {
        Red, 
        Green, 
        Blue, 
        Purple, 
        Orange, 
        Lime, 
        Emerald, 
        Teal, 
        Cyan, 
        Cobalt,
        Indigo, 
        Violet, 
        Pink, 
        Magenta, 
        Crimson, 
        Amber, 
        Yellow, 
        Brown, 
        Olive, 
        Steel, 
        Mauve, 
        Taupe, 
        Sienna
    }
}
